### ISSUE TITLE
Highlighting the background color of text sent to REPL

### ISSUE THREAD

**Issue by aqjune** [monadius/vscode-hol-light#1]
It would be great if the background color of text sent to REPL is highlighted.

I have a proof which has a tactic that runs for a very long time, so while the tactic is run on REPL I would like to edit another part of the source code.
However, after editing the different part, I often miss the tactic I had sent to REPL before.
If the text that was sent to REPL remains highlighted, this issue can be nicely resolved.

Editors for Coq (e.g., CoqIDE: https://www.youtube.com/watch?v=ngM2N98ppQE , ProofGeneral: https://www.youtube.com/watch?v=l6zqLJQCnzo) have a similar feature. `.` in Coq is equivalent to `;;` in OCaml.

**Comment by monadius** [comment]
I created a preliminary release for this feature (https://github.com/monadius/vscode-hol-light/releases/tag/0.2.0). Text which is sent to the HOL Light REPL is highlighted. It does not work in the same way as in CoqIDE: only the text that was most recently sent to REPL is highlighted. It is possible to implement something similar to CoqIDE (all text processed by REPL is highlighted) but I am not sure that it will work well with HOL Light.

**Comment by aqjune** [comment]
Thanks! I tried your patch and it is working great!

> It is possible to implement something similar to CoqIDE (all text processed by REPL is highlighted)  but I am not sure that it will work well with HOL Light.

Yes, I also think that HOL Light and Coq might not be exactly in a same situation because HOL Light users might want to evaluate statements out-of-order.

Please let me know whenever new features are added! I will close this issue and open new ones if I want new features or issues are found.
