### ISSUE TITLE
Search command not working properly when `_` is used in the term ident

### ISSUE THREAD

**Issue by yiyuan-cao** [monadius/vscode-hol-light#13]
If I use the `search` function directly, it works as usual:
```sh
# search[`list_of_seq`];;
Warning: inventing type variables
- : (string * thm) list =
[("EL_LIST_OF_SEQ", |- forall s m n. m < n ==> EL m (list_of_seq s n) = s m);
 ("LENGTH_LIST_OF_SEQ", |- forall s n. LENGTH (list_of_seq s n) = n);
 ("LIST_OF_SEQ_EQ_NIL", |- forall s n. list_of_seq s n = [] <=> n = 0);
 ("list_of_seq",
  |- list_of_seq s 0 = [] /\
     list_of_seq s (SUC n) = APPEND (list_of_seq s n) [s n])]
```

However, if I issue a search command:
<img width="594" alt="image" src="https://github.com/user-attachments/assets/58a309fd-9d1e-47ae-be31-1c4f4d9093ad">
<img width="474" alt="image" src="https://github.com/user-attachments/assets/6ee16d64-3cc3-4a31-b763-5b33ccb0b320">

It seems like a problem about handling underlines in term names?

**Comment by monadius** [comment]
Thank you for reporting this issue! It should be fixed in the latest extension version (2.1.2).
