### ISSUE TITLE
Syntax highlighting of type annotation

### ISSUE THREAD

**Issue by aqjune** [monadius/vscode-hol-light#2]
I found a couple of cases where type annotation `e:ty` is not highlighted. Would it be straightforward to fix?

![synhl](https://github.com/monadius/vscode-hol-light/assets/6484889/7547b330-40cd-4568-9895-9307da5eaa5a)

**Comment by monadius** [comment]
It should be easy to fix. I am traveling right now. So I will fix this bug
when I return home next week.

**Comment by monadius** [comment]
I implemented a more sophisticated regular expression for HOL Light type annotations in the new release. It is still not possible to highlight multiline type annotations correctly or types which use custom type constructors (currently, the only supported constructors are `list`, `group`, and `finite_sum`).

**Comment by aqjune** [comment]
Thanks, it works wonderfully. :)

Do you mind if you add `word` as a highlighted type constructor? You don't need to publish it as a new version because I git pull and build your plugin directly.

**Comment by monadius** [comment]
I added `word` to the list of known type constructors.
