### ISSUE TITLE
Highlighting matching parenthesis?

### ISSUE THREAD

**Issue by aqjune** [monadius/vscode-hol-light#4]
(note: another existing vscode plugin or default feature might already support this, but wanted to share this topic first and discuss)

I would like to suggest that opening-closing parentheses in a HOL Light term are highlighted with the same color, and the matching parenthesis on the cursor to be highlighted with a small box.
vscode-hol-light already does this for parentheses in OCaml code, but not in HOL Light terms.

**Comment by aqjune** [comment]
This looks like a limitation of the built-in feature of VSCode: https://github.com/microsoft/vscode/issues/146453
Waiting for its fix might be one possible option.

**Comment by monadius** [comment]
I implemented this feature in the latest commit. Opening-closing parentheses should be correctly highlighted in HOL Light terms. Please let me know if you find any issues.

**Comment by aqjune** [comment]
This worked wonderfully!! Thanks a lot :)
