### ISSUE TITLE
Shortcut for Windows

### ISSUE THREAD

**Issue by aqjune** [monadius/vscode-hol-light#5]
In Windows, the default shortcuts starting with `Ctrl + C` overlap with a shortcut for text copy.

Would it be a good idea if the default shortcuts of the plugin start with `Alt + C` in Windows instead? It still overlaps with the shortcut of `toggleSearchEditorCaseSensitive` which exists in VSCode by default, but I think it is less intensively used than a text copy.

**Comment by monadius** [comment]
What do you think about the following shortcuts: `Alt + e` for sending statements to REPL (execute), `Alt + l` for executing a single line tactic, `Alt + m` for executing a multiline tactic, `Alt + g` for setting a goal, etc.? In other words, replace `Ctrl + C, {command key}` with `Alt + {command key}`. I don't think that `Alt + {something}` is often used in VSCode. One problem with `Alt` is that a single `Alt` press switches the focus to the main menu.

**Comment by aqjune** [comment]
It sounds great to me - thanks!

**Comment by monadius** [comment]
Updated in the latest commit.
