### ISSUE TITLE
Giving a special font color to functions creating axioms

### ISSUE THREAD

**Issue by aqjune** [monadius/vscode-hol-light#7]
Suggestion: it would be great if `CHEAT_TAC`, `new_axiom` and `mk_thm` are specially highlighted so that they are immediately visible even without carefully looking into the code.

What about a red font color? Or even its background red?

**Comment by monadius** [comment]
`CHEAT_TAC`, `new_axiom`, and `mk_thm` are displayed with red color and underlined in the new version (1.1.0).

I don't know a simple way to change the background color of selected words.
